apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: test-result-tkn-go-gitops-on-push
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task-0: "https://raw.githubusercontent.com/redhat-appstudio/tssc-sample-pipelines/main/pac/tasks/git-clone.yaml"
  labels:
    argocd/app-name: test-result-tkn-go
    janus-idp.io/tekton: test-result-tkn-go
    backstage.io/kubernetes-id: test-result-tkn-go
    backstage.io/kubernetes-namespace: tssc-app
    app.kubernetes.io/part-of: test-result-tkn-go
spec:
  params:
    - name: git-url
      value: '{{repo_url}}'
    - name: revision
      value: '{{revision}}'
  pipelineRef:
    name: test-deployment-image
  workspaces:
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi