apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-result-tkn-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-result-tkn-go 
  name: test-result-tkn-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: test-result-tkn-go 
